In [1]:
# %load test_rigid_transform_3D.py
#!/usr/bin/env python3

from numpy import *
from math import sqrt

from rigid_transform_3D import rigid_transform_3D

# Test with random data

# Random rotation and translation
R = mat(random.rand(3,3))
t = mat(random.rand(3,1))

# make R a proper rotation matrix, force orthonormal
U, S, Vt = linalg.svd(R)
R = U*Vt

# remove reflection
if linalg.det(R) < 0:
   Vt[2,:] *= -1
   R = U*Vt

# number of points
n = 10

# A = mat(random.rand(3, n));
A = array(random.rand(3, n));
B = R*A + tile(t, (1, n))

# Recover R and t
ret_R, ret_t = rigid_transform_3D(A, B)

# Compare the recovered R and t with the original
B2 = (ret_R*A) + tile(ret_t, (1, n))

# Find the root mean squared error
err = B2 - B
err = multiply(err, err)
err = sum(err)
rmse = sqrt(err/n);

print("Points A")
print(A)
print("")

print("Points B")
print(B)
print("")

print("Ground truth rotation")
print(R)

print("Recovered rotation")
print(ret_R)
print("")

print("Ground truth translation")
print(t)

print("Recovered translation")
print(ret_t)
print("")

print("RMSE:", rmse)

if rmse < 1e-5:
    print("Everything looks good!\n");
else:
    print("Hmm something doesn't look right ...\n");


Points A
[[0.23799564 0.54122062 0.1064581  0.85302337 0.23278242 0.16491722
  0.7163607  0.0228284  0.16114075 0.84832998]
 [0.42691851 0.48422478 0.83152716 0.64128146 0.99613637 0.16410261
  0.01959253 0.24674879 0.24666136 0.08618707]
 [0.48177331 0.997357   0.52684765 0.46619193 0.58988058 0.33294544
  0.4504468  0.14366469 0.62787923 0.98440047]]

Points B
[[0.75528606 1.07639213 0.41141621 1.04366257 0.41061404 0.83346967
  1.34878096 0.6262802  0.85999528 1.54852705]
 [1.05938033 1.33603665 1.27577808 1.62698586 1.48623649 0.8058843
  1.07251117 0.76100246 0.88329638 1.24332179]
 [0.96151935 1.38743966 1.09556233 0.82325757 1.14784795 0.79968773
  0.753384   0.66587829 1.09484855 1.24111597]]

Ground truth rotation
[[ 0.70346284 -0.65256029  0.28161161]
 [ 0.66513888  0.74408233  0.06270373]
 [-0.25046019  0.14320109  0.95747749]]
Recovered rotation
[[ 0.70346284 -0.65256029  0.28161161]
 [ 0.66513888  0.74408233  0.06270373]
 [-0.25046019  0.14320109  0.95747749]]

Ground trut

In [2]:
ret_t

matrix([[0.73078208],
        [0.55320867],
        [0.49870549]])

In [3]:
from numpy import *
from math import sqrt


In [4]:
# number of points
n = 10
# Random rotation and translation
R = mat(random.rand(3,3))
t = mat(random.rand(3,1))
# make R a proper rotation matrix, force orthonormal
U, S, Vt = linalg.svd(R)
R = U*Vt

A = array(random.rand(3, n));
B = R*A + tile(t, (1, n))

In [23]:
linalg.det(U*Vt)

-0.9999999999999994

In [24]:
print(R)
print(Vt.T * U.T)

[[-0.12520083  0.59492912  0.79396731]
 [ 0.20204427  0.79878333 -0.56667743]
 [ 0.97134076 -0.08946806  0.22021036]]
[[-0.12520083  0.20204427  0.97134076]
 [ 0.59492912  0.79878333 -0.08946806]
 [ 0.79396731 -0.56667743  0.22021036]]


In [5]:
print("shape of a is:",A.shape, "b:",B.shape)
print(type(A))
print(type(B))

shape of a is: (3, 10) b: (3, 10)
<class 'numpy.ndarray'>
<class 'numpy.matrix'>


In [6]:
# try run rigid_t here------------------------
# find mean column wise
centroid_A = mean(A, axis=1)# 1: row
centroid_B = mean(B, axis=1)


In [7]:
print("shape of a is:",centroid_A.shape, "b:",centroid_B.shape)
print(centroid_A)
print(centroid_B)

shape of a is: (3,) b: (3, 1)
[0.40183286 0.59000793 0.50856446]
[[1.40736467]
 [1.11049891]
 [0.47682378]]


In [38]:
AM = (1/(A.shape[0]*A.shape[1]))*sum(A)
AM

0.5001350855093033

In [39]:
sum(A)

15.004052565279098

In [43]:
type(A)

numpy.ndarray

In [40]:
mean(A, axis=1)

array([0.40183286, 0.59000793, 0.50856446])

In [42]:
R*1+1

matrix([[0.87479917, 1.59492912, 1.79396731],
        [1.20204427, 1.79878333, 0.43332257],
        [1.97134076, 0.91053194, 1.22021036]])